### ISSUE TITLE
spelling error in paper

### ISSUE THREAD

**Issue by Michael-Meade** [johnnyzn/DW-GAN#1]
![image](https://user-images.githubusercontent.com/47438130/149585697-503d4912-aae5-491f-8fab-0828d804a258.png)
minutes is misspelled in the paper at https://arxiv.org/pdf/2201.02799.pdf

**Comment by johnnyzn** [comment]
@Michael-Meade Thanks for the correction. I just submitted the corrected paper, and it is processing.
